# Generated by Django 4.2 on 2024-05-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_major", models.IntegerField(default=0)),
                ("double_major", models.IntegerField(default=0)),
                ("second_major", models.IntegerField(default=0)),
                ("outside", models.IntegerField(default=0)),
                ("liberal", models.IntegerField(default=0)),
                ("minor_major", models.IntegerField(default=0)),
                ("teaching", models.IntegerField(default=0)),
                ("self_selction", models.IntegerField(default=0)),
                ("total_credit", models.IntegerField(default=0)),
                ("total_score", models.FloatField(default=0)),
                ("main_test_pass", models.BooleanField(default=False)),
                ("double_test_pass", models.BooleanField(default=False)),
                (
                    "foreign_pass",
                    models.IntegerField(
                        choices=[
                            (1, "None"),
                            (2, "FLEX"),
                            (3, "FLEX Speaking"),
                            (4, "TOEIC"),
                            (5, "TOEIC Speaking"),
                            (6, "TOEFL"),
                            (7, "IELTS"),
                            (8, "OPIc"),
                            (9, "Foreign Language Certification Replacement"),
                        ],
                        default=1,
                    ),
                ),
            ],
        ),
    ]
