# Generated by Django 5.0.4 on 2024-05-29 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_major_credit', models.IntegerField(blank=True, null=True, verbose_name='1전공')),
                ('double_major_credit', models.IntegerField(blank=True, null=True, verbose_name='이중전공')),
                ('second_major_credit', models.IntegerField(blank=True, null=True, verbose_name='2전공')),
                ('outside_credit', models.IntegerField(blank=True, null=True, verbose_name='실외')),
                ('liberal_credit', models.IntegerField(blank=True, null=True, verbose_name='교양')),
                ('minor_major_credit', models.IntegerField(blank=True, null=True, verbose_name='부전공')),
                ('teaching_credit', models.IntegerField(blank=True, null=True, verbose_name='교직')),
                ('self_selection_credit', models.IntegerField(blank=True, null=True, verbose_name='자선')),
                ('total_credit', models.IntegerField(blank=True, null=True, verbose_name='총취득')),
                ('total_score', models.FloatField(blank=True, null=True, verbose_name='총평점')),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_test_pass', models.BooleanField(blank=True, null=True, verbose_name='본전공 통과')),
                ('double_test_pass', models.BooleanField(blank=True, null=True, verbose_name='이중전공 통과')),
                ('foreign_certification', models.IntegerField(blank=True, choices=[(1, '해당없음'), (2, 'FLEX'), (3, 'FLEX 스피킹'), (4, 'TOEIC'), (5, 'TOEIC 스피킹'), (6, 'TOEFL'), (7, 'IELTS'), (8, 'OPIc'), (9, '외국어인증대체과정')], null=True, verbose_name='외국어인증')),
            ],
        ),
        migrations.CreateModel(
            name='UserLiberalCompulsory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, null=True, verbose_name='상태')),
            ],
        ),
        migrations.CreateModel(
            name='UserMajorCompulsory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, null=True, verbose_name='상태')),
            ],
        ),
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.IntegerField(blank=True, null=True, verbose_name='학번')),
                ('major_type', models.IntegerField(choices=[(1, '전공심화'), (2, '이중전공'), (3, '부전공'), (4, '전공심화+부전공')], default=1, verbose_name='전공유형')),
                ('transfer', models.BooleanField(blank=True, null=True, verbose_name='편입생')),
                ('foreign_st', models.BooleanField(blank=True, null=True, verbose_name='외국인전형')),
                ('double_major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_double', to='major.major', verbose_name='이중전공')),
                ('main_major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_main', to='major.major', verbose_name='본전공')),
                ('minor_major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_minor', to='major.major', verbose_name='부전공')),
            ],
        ),
    ]
