# Generated by Django 4.2 on 2024-05-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="self_selction",
            new_name="self_selection",
        ),
        migrations.AlterField(
            model_name="profile",
            name="foreign_pass",
            field=models.IntegerField(
                choices=[
                    (1, "해당없음"),
                    (2, "FLEX"),
                    (3, "FLEX 스피킹"),
                    (4, "TOEIC"),
                    (5, "TOEIC 스피킹"),
                    (6, "TOEFL"),
                    (7, "IELTS"),
                    (8, "OPIc"),
                    (9, "외국어인증대체과정"),
                ],
                default=1,
            ),
        ),
    ]
