# Generated by Django 5.0.4 on 2024-05-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='double_major',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='liberal',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='main_major',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='minor_major',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='outside',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='second_major',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='self_selection',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='teaching',
        ),
        migrations.AddField(
            model_name='credit',
            name='double_major_credit',
            field=models.IntegerField(null=True, verbose_name='이중전공'),
        ),
        migrations.AddField(
            model_name='credit',
            name='liberal_credit',
            field=models.IntegerField(null=True, verbose_name='교양'),
        ),
        migrations.AddField(
            model_name='credit',
            name='main_major_credit',
            field=models.IntegerField(null=True, verbose_name='1전공'),
        ),
        migrations.AddField(
            model_name='credit',
            name='minor_major_credit',
            field=models.IntegerField(null=True, verbose_name='부전공'),
        ),
        migrations.AddField(
            model_name='credit',
            name='outside_credit',
            field=models.IntegerField(null=True, verbose_name='실외'),
        ),
        migrations.AddField(
            model_name='credit',
            name='second_major_credit',
            field=models.IntegerField(null=True, verbose_name='2전공'),
        ),
        migrations.AddField(
            model_name='credit',
            name='self_selection_credit',
            field=models.IntegerField(null=True, verbose_name='자선'),
        ),
        migrations.AddField(
            model_name='credit',
            name='teaching_credit',
            field=models.IntegerField(null=True, verbose_name='교직'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='total_credit',
            field=models.IntegerField(null=True, verbose_name='총취득'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='total_score',
            field=models.FloatField(null=True, verbose_name='총평점'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='double_test_pass',
            field=models.BooleanField(null=True, verbose_name='이중전공 통과'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='foreign_pass',
            field=models.IntegerField(choices=[(1, '해당없음'), (2, 'FLEX'), (3, 'FLEX 스피킹'), (4, 'TOEIC'), (5, 'TOEIC 스피킹'), (6, 'TOEFL'), (7, 'IELTS'), (8, 'OPIc'), (9, '외국어인증대체과정')], null=True, verbose_name='외국어인증'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='main_test_pass',
            field=models.BooleanField(null=True, verbose_name='본전공 통과'),
        ),
        migrations.AlterField(
            model_name='liberalcompulsorysubject',
            name='status',
            field=models.BooleanField(null=True, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='majorcompulsorysubject',
            name='status',
            field=models.BooleanField(null=True, verbose_name='상태'),
        ),
    ]
