# Generated by Django 4.2 on 2024-05-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_rename_self_selction_profile_self_selection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompulsorySubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=False)),
            ],
        ),
    ]
