# Generated by Django 5.0.4 on 2024-05-29 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_credit_double_major_remove_credit_liberal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basic',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='credit',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='extra',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='liberalcompulsorysubject',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='majorcompulsorysubject',
            old_name='user_id',
            new_name='user',
        ),
    ]
