# Generated by Django 4.2 on 2024-05-27 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0004_myuser_is_active_myuser_is_admin_myuser_is_staff"),
        ("profiles", "0003_compulsorysubject"),
    ]

    operations = [
        migrations.AddField(
            model_name="compulsorysubject",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="compulsorysubject",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.subject",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
