# Generated by Django 5.0.4 on 2024-05-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_user_id_basic_user_rename_user_id_credit_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic',
            name='student_no',
            field=models.CharField(max_length=10, null=True, verbose_name='학번'),
        ),
    ]
