# Generated by Django 5.0.4 on 2024-05-24 01:39

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='이메일')),
                ('nickname', models.CharField(max_length=20, unique=True, verbose_name='닉네임')),
                ('student_no', models.CharField(max_length=10, null=True, unique=True, verbose_name='학번')),
                ('major_type', models.IntegerField(choices=[(1, '전공심화'), (2, '이중전공'), (3, '부전공'), (4, '전공심화+부전공')], default=1, verbose_name='전공유형')),
                ('transfer', models.BooleanField(blank=True, default=False, verbose_name='편입생')),
                ('foreign', models.BooleanField(blank=True, default=False, verbose_name='외국인전형')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('double_major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_double', to='major.major', verbose_name='이중전공')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('main_major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_main', to='major.major', verbose_name='본전공')),
                ('minor_major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_minor', to='major.major', verbose_name='부전공')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
