# Generated by Django 5.0.4 on 2024-05-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='major_type',
            field=models.IntegerField(choices=[(1, '전공심화'), (2, '이중전공'), (3, '부전공'), (4, '전공심화+부전공')], default=1, verbose_name='전공유형'),
        ),
    ]
