# Generated by Django 5.0.4 on 2024-05-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_major_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='student_no',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='학번'),
        ),
    ]
