# Generated by Django 5.0.4 on 2024-05-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classof',
            name='year',
            field=models.IntegerField(verbose_name='년도'),
        ),
    ]
