# Generated by Django 4.2 on 2024-05-27 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_myuser_is_active_myuser_is_admin_myuser_is_staff"),
        ("requirement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirement",
            name="major_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.major",
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="major_type",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="student_no",
            field=models.CharField(max_length=2),
        ),
    ]
