# Generated by Django 5.0 on 2024-05-26 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("requirement", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirement",
            name="major_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.major",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="requirement",
            unique_together={("major_id", "student_no", "major_type")},
        ),
    ]
