# Generated by Django 4.2 on 2024-05-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requirement", "0002_requirement_major_id_requirement_major_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirement",
            name="practical_foreign",
            field=models.IntegerField(default=0),
        ),
    ]
